services:
  db: 
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
  www:
    build: ./www
    volumes:
      - "./www:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
    depends_on:
      - db
networks:
  lamp-docker:
    driver: bridge